name = "CAGD"
uuid = "ef2cacc4-7e30-11ea-14af-9fa836e29f64"
authors = ["eOnofri04 <elia.onofri@mensa.it>"]
version = "0.1.0"
keywords = ["geometry", "topology", "cell-complex", "chain-complex"]
license = "MIT"
desc = "LAR submodule"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
IntervalTrees = "524e6230-43b7-53ae-be76-1e9e4d08d11b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearAlgebraicRepresentation = "95167b0c-186a-594b-a231-52369c6de044"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"